services:
  db:
    image: odegichristine/messaging-app:latest
    container_name: messaging_db
    restart: always
    # Done for the checker, not best practice
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: messaging_db
      #MYSQL_DB: messaging_db
      MYSQL_USER: messaging_user
      MYSQL_PASSWORD: messaging_pass
#    env_file:
#      - .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: messaging_web
    command: sh -c "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data: